### ISSUE TITLE
could not commit jpa transaction.

### ISSUE THREAD

**Issue by iamankit555** [eazybytes/spring#10]
Hi madan.. I am getting error while updating the profile details. error is triggering when jpa is trying to update the address details.
Error message : could not commit jpa transaction.
Can you please help me why it is giving this error. I have been debugging for the last one month but could not able to solve this error.

I tried to run your code that one is also giving same error.

![image](https://github.com/eazybytes/spring/assets/55355863/1f327f82-9e8e-4eed-8a72-b280b017af02)

**Comment by eazybytes** [comment]
Hi,

I would request to compare your code with mine and correct any mismatches. If all looks good from your side, but still facing the error, please share your exact project with me via GitHub repo. So that I can check the same.

**Comment by iamankit555** [comment]
Here is my github repo.. thanks for your support.
udemy video no : 177
Error hitting while updaing the profile details
[](https://github.com/iamankit555/firstSpringBootProject)

**Comment by iamankit555** [comment]
Hi..Madan sir.. please help here.

**Comment by eazybytes** [comment]
I checked your code and since it is missing the below property inside application.properties, you are facing the error. Please add the same and issue should get resolved. I discussed about this inside the lecture 173. Quick Tip - To Disable the javax validations in Spring Data JPA

**spring.jpa.properties.javax.persistence.validation.mode=none**

Next time for any question, please post inside Udemy Q&A to get fast reponse.

**Comment by iamankit555** [comment]
Thanks sir.. Now it is working fine.. Sure next time will post the query inside udemy Q&A
