### ISSUE TITLE
example 21  application

### ISSUE THREAD

**Issue by mounika-12-code** [eazybytes/spring#7]
Hello 21 example have lot of errors even I tried I lot to rectify plz do check once.

**Comment by eazybytes** [comment]
This can be due to Lombok annotations.  For Lombok annotations to work, we need to enable annotation processing inside the IDE. 

Inside IntelliJ IDE, you can go to Preferences and search for 'Annotation Processors'. Post that please make sure to check the 'Enable annotation processing' option and do a maven clean build.

Thanks

**Comment by mounika-12-code** [comment]
But I am using eclipse what i need to do

**Comment by eazybytes** [comment]
Inside Eclipse also, we need to follow similar steps. Please check below link,

https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.jst.ws.cxf.doc.user%2Ftasks%2Fconfiguring_jaxws_annotation_processing.html

If the above is not working, please refer to the below official link on how to setup Lombok in Eclipse,

https://projectlombok.org/setup/eclipse

Thanks
